[tox]
envlist =
    lint
    test
recreate = true

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
scripts_path = {tox_root}/scripts
all_path = {[vars]src_path} {[vars]scripts_path} {[vars]tests_path}

[testenv:format]
description = Apply coding style standards to code
dependency_groups = format
commands =
    ruff check --fix {[vars]all_path}
    ruff format {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
dependency_groups =
    lint
    format
commands =
    codespell {[vars]all_path}
    ruff check {[vars]all_path}
    ruff format --check {[vars]all_path}
    ty check {[vars]src_path}

[testenv:test]
description = Run unit tests
dependency_groups = test
commands =
    pytest {[vars]tests_path}
