[tox]
envlist =
    lint
recreate = true

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path}

[testenv:format]
description = Apply coding style standards to code
dependency_groups = format
commands =
    isort {[vars]all_path}
    black {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
dependency_groups =
    lint
    format
commands =
    black --check --diff {[vars]all_path}
    codespell {[vars]all_path}
    isort --check-only --diff {[vars]all_path}
    pflake8 {[vars]all_path}
    pylint {[vars]src_path}
